config/routes.rb
Rails.application.routes.draw do

resources :cars

root 'cars#index'

end

app/models/car.rb
class Car < ActiveRecord::Base

  scope :newest_first, -> { order("created_at DESC") }
  scope :most_recent_five, -> { newest_first.limit(5) }
  scope :created_before, ->(time) { where("created_at < ?", time) }

	# def self.created_before(time)
	# 	where("create_at < ?", time)
	# end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
	
	def index
		@cars = Car.all
		@most_recent_cars = Car.most_recent_five
	end

	def show
		@car = Car.find(params[:id])
	end

	def new
		@car = Car.new
	end

	def edit
		@car = Car.find(params[:id])
	end

	def update
		@car = Car.find(params[:id])

		if @car.update_attributes(car_params)
			redirect_to "/cars/#{@car.id}"
		else
			render :edit
		end
	end

	def create
		@car = Car.new(car_params)
			if @car.save
				redirect_to cars_url
			else

				render :new
		end
	end

	def destroy
		@car = Car.find(params[:id])
		@car.destroy
		redirect_to cars_url
	end

	private
	def car_params
		params.require(:car).permit(:manufacturer, :model, :url)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/edit.html.erb
<h1>Edit Car</h1>

<p>
	<%= link_to "Back", @car %>
</p>

<%= form_for @car do |c| %>

	<p>
		<%= c.label "model" %>
		<%= c.text_field "model" %>
	</p>
	<p>
		<%= c.label "manufacturer" %>
		<%= c.text_field "manufacturer" %>
	</p>
	<p>
		<%= c.label"url" %>
		<%= c.text_field"url" %>
	</p>
	<p>
		<%= c.submit "Submit" %>
	</p>
	<% end %>

app/views/cars/index.html.erb
<h1>Welcome to Autogur (<%= @cars.length %>)</h1>
<%= link_to "Add Car", "/cars/new" %>

<% @cars.each do |car| %>
	<p><%= car.model %>, 
	   <%= car.manufacturer %>
	</p>
	<%= link_to image_tag(car.url), "/cars/#{car.id}" %>
<% end %>

<h1>Most recent cars</h1>

<ul>
  <% @most_recent_cars.each do |car| %>
    <li><%= car.model %></li>
  <% end %>
</ul>

app/views/cars/new.html.erb
<h1>Add a Car</h1>
<%= link_to "Back to Autogur", cars_url %> 
<%= form_for @car do |c| %>
	<p>
		<%= c.label "model" %>
		<%= c.text_field "model" %>
	</p>
	<p>
		<%= c.label "manufacturer" %>
		<%= c.text_field "manufacturer" %>
	</p>
	<p>
		<%= c.label"url" %>
		<%= c.text_field"url" %>
	</p>
	<p>
		<%= c.submit "Submit" %>
	</p>
	<% end %>

app/views/cars/show.html.erb
<%= link_to "Back to Autogur", cars_url %> | <%= link_to "Edit", edit_car_path(@car) %> | <%= link_to 'Delete', @car, :confirm => "Are you sure you want to delete this car?", :method => :delete %>

<p><%= @car.model %>, <%= @car.manufacturer %></p>
<%= image_tag @car.url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Autogur</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>